default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: giftbrain_development

test:
  <<: *default
  database: giftbrain_test

production:
  primary:
    <<: *default
    database: giftbrain_production
    username: giftbrain_production_user
    password: <%= ENV["POSTGRES_PASSWORD"] %>
    host: <%= ENV["DB_HOST"] %>
    port: 5432
