default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10

development:
  <<: *default
  database: giftbrain_development

test:
  <<: *default
  database: giftbrain_test

production:
  primary:
    <<: *default
    database: giftbrain_production
    username: giftbrain_production_user
    password: <%= ENV["POSTGRES_PASSWORD"] %>
    host: 192.168.1.38
    port: 5432
