service: giftbrain
image: cyberice2077/giftbrain:latest

ssh:
  user: ice-server

servers:
  web:
    - 192.168.1.38

builder:
  local: true
  arch: amd64

registry:
  username: cyberice2077
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    DB_HOST: 192.168.1.38
    RAILS_LOG_LEVEL: debug
    DB_USER: giftbrain
    DB_PASSWORD: ${GIFTBRAIN_DATABASE_PASSWORD}
    DB_NAME: giftbrain_production

proxy:
  ssl: true
  host: giftbrain.app

volumes:
  - "giftbrain_storage:/rails/storage"

asset_path: /rails/public/assets

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"
