service: giftbrain
image: cyberice2077/giftbrain

ssh:
  user: ice-server

servers:
  web:
    - 192.168.1.38
  db:
    - 192.168.1.38

builder:
  local: true
  arch: amd64

registry:
  username: cyberice2077
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    RAILS_LOG_LEVEL: debug
    DB_USER: giftbrain
    DB_PASSWORD: ${GIFTBRAIN_DATABASE_PASSWORD}
    DB_NAME: giftbrain_production

accessories:
  db:
    image: postgres:16
    roles:
      - db
    env:
      POSTGRES_USER: giftbrain
      POSTGRES_PASSWORD: ${GIFTBRAIN_DATABASE_PASSWORD}
      POSTGRES_DB: giftbrain_production
    volumes:
      - giftbrain_postgres:/var/lib/postgresql/data
    port: 5432

proxy:
  ssl: true
  host: giftbrain.app

volumes:
  - "giftbrain_storage:/rails/storage"

asset_path: /rails/public/assets

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"
