# Name of your application. Used to uniquely configure containers.
service: giftbrain

# Name of the container image.
image: cyberice2077/giftbrain

# Deploy to these servers.
servers:
  web:
    - 192.168.1.38
  job:
    hosts:
      - 192.168.1.38
    cmd: bundle exec sidekiq

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Remove this section when using multiple web servers and ensure you terminate SSL at your load balancer.
#
# Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
# proxy:
#   ssl: true
#   host: giftbrain.app
#   app_port: 3000

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: cyberice2077

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
  clear:
    # Set number of cores available to the application on each server (default: 1).
    # WEB_CONCURRENCY: 2

    # Match this to any external database server to configure Active Record correctly
    # Use giftbrain-db for a db accessory server on same machine via local kamal docker network.
    DB_HOST: 192.168.1.38
    POSTGRES_USER: giftbrain_production_user
    POSTGRES_DB: giftbrain_production

    # Log everything from Rails
    RAILS_LOG_LEVEL: info

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal logs -r job" will tail logs from the first server in the job section.
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

# Use a persistent storage volume for sqlite database files and local Active Storage files.
# Recommended to change this to a mounted volume path that is backed up off server.
volumes:
  - "giftbrain_storage:/rails/storage"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
asset_path: /rails/public/assets

# Configure the image builder.
builder:
  arch: amd64

ssh:
  user: ice-server

accessories:
  # db:
  #   image: postgres:16
  #   roles:
  #     - web
  #   env:
  #     clear:
  #       POSTGRES_USER: giftbrain_production_user
  #       POSTGRES_DB: giftbrain_production
  #     secret:
  #       - POSTGRES_PASSWORD
  #   directories:
  #     - data:/var/lib/postgresql/data
  tunnel:
    image: cloudflare/cloudflared:latest
    roles:
      - web
    files:
      - ./.kamal/cloudflare/credentials.json:/etc/cloudflared/credentials.json
      - ./.kamal/cloudflare/config.yml:/etc/cloudflared/config.yml
    cmd: tunnel --config /etc/cloudflared/config.yml run
  redis:
    image: redis:7.0.15
    roles:
      - web
      - job
    volumes:
      - data:/data
  ollama:
    image: ollama/ollama:latest
    roles:
      - job
    env:
      clear:
        OLLAMA_MODELS: /models
    volumes:
      - ollama_models:/models
    # RUN THIS: docker exec -it giftbrain-ollama ollama pull phi4-mini:3.8b
